from enum import Enum

class Category(Enum):
    INDEX = 0
    HOGWARTS_HOUSE = 1
    FIRST_NAME = 2
    LAST_NAME = 3
    BIRTHDAY = 4
    BEST_HAND = 5
    ARITHMANCY = 6
    ASTRONOMY = 7
    HERBOLOGY = 8
    DEFENSE_AGAINST_THE_DARK_ARTS = 9
    DIVINATION = 10
    MUGGLE_STUDIES = 11
    ANCIENT_RUNES = 12
    HISTORY_OF_MAGIC = 13
    TRANSFIGURATION = 14
    POTIONS = 15
    CARE_OF_MAGICAL_CREATURES = 16
    CHARMS = 17
    FLYING = 18